name: Build on Contentful Publish Event

on:
  repository_dispatch:
    types: [publish-event]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Build page with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Deploy page
        uses: actions/deploy-pages@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
